### PR TITLE
This small change fix ignoring in fuzzy.Find()

### PR DESCRIPTION
**Pull request by greeschenko**
On screenshot you can see find results with different cmd strings

result 2 is with this patch 
result 3 from old version

20240412-164350_1920x1080

### CODE REVIEW

**Comment by girishji** [comment]
This is not the correct change. `./client/node_modules` should be in `relpaths`, not in `dirs`. Did you put `./client/node_modules` in .gitignore?
Can you update and try again.

**Comment by girishji** [comment]
https://github.com/girishji/scope.vim/commit/2ee33f1430100ebf8243b27973f0f50c3b4c5a7a

**Comment by greeschenko** [comment]
Yes ./client/node_modules  is in .gitignore and it not work for me in old version 
now I try new version and its doesn't work 

20240413-185624_1920x1080

**Comment by greeschenko** [comment]
work with change ./client/node_modules/ to ./client/node_modules but in git for ignoring work both variants

**Comment by girishji** [comment]
https://github.com/girishji/scope.vim/commit/30cab4f3fc7922828657dbe69619b55e7f028aad

Fixed. Please try now.

**Comment by greeschenko** [comment]
Thank you very match its work!

**Pull request closed without merging**
